## NumPy Indeximg and Selection

In [2]:
import numpy as np

In [2]:
arr = np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
arr1 = np.arange(10,100,5)
arr1

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [6]:
len(arr1)

18

In [8]:
arr1[-1]

95

In [9]:
arr1[6]

40

In [11]:
arr1[1:11:2]

array([15, 25, 35, 45, 55])

In [12]:
arr1[::-1]

array([95, 90, 85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15,
       10])

###  Filtering

In [14]:
arr2 = np.array([1,2,1010,4,108,18,71,610])
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [15]:
arr2 < 100

array([ True,  True, False,  True, False,  True,  True, False])

In [16]:
np.where(arr>100) # where function outputs index location of values meeting the condition

(array([2, 4, 7], dtype=int64),)

In [17]:
np.where(arr<100)

(array([0, 1, 3, 5, 6], dtype=int64),)

### Indexing a 2D array

In [3]:
arr_2d = np.array(([1,2,3],[4,5,6],[7,8,9]))
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr_2d[1:,:2]

array([[4, 5],
       [7, 8]])

In [5]:
arr_2d[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr_2d[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [10]:
arr_2d[2:]

array([[7, 8, 9]])

In [11]:
arr_2d[:1]

array([[1, 2, 3]])

In [12]:
arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr_2d[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr_2d[1:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [13]:
arr_2d[2:,:]

array([[7, 8, 9]])

In [14]:
arr_2d[:,:1]

array([[1],
       [4],
       [7]])

In [15]:
arr_2d[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [16]:
arr_2d[1:,:2]

array([[4, 5],
       [7, 8]])

In [17]:
arr_2d[2:,:2]

array([[7, 8]])

In [19]:
arr_2d[1,:]

array([4, 5, 6])

In [20]:
arr_2d[2,:]

array([7, 8, 9])

In [21]:
arr_2d[2,:1]

array([7])

In [22]:
arr_2d[1,:2]

array([4, 5])

In [23]:
arr_2d.shape

(3, 3)

In [24]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])