## numpy

NumPy is a powerful Python library used for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.

Array Handling: NumPy introduces the ndarray object, which is a fast, efficient container for large datasets in Python. It's much more efficient than Python's built-in lists for numerical data.

Mathematical Operations: NumPy provides a wide range of mathematical functions, such as linear algebra operations, Fourier transforms, random number generation, and statistical functions.

Data Manipulation: NumPy allows for easy reshaping, slicing, and indexing of arrays. This makes it straightforward to manipulate and access data.

Integration with Other Libraries: NumPy is the foundation for many other libraries in Python, including pandas, scikit-learn, and TensorFlow. It provides the numerical backbone for data analysis and machine learning.

Performance: NumPy operations are executed in C, making them much faster than equivalent Python code. This performance boost is crucial for handling large datasets

In [1]:
!pip install numpy

## Using NumPy

In [2]:
import numpy as np

## Arrays

In [4]:
# creating an empty array
# default datatype of elements of array is float
arr1 = np.array([])
arr1

array([], dtype=float64)

In [7]:
my_list = [1,2,3,4,5,6,7]
print(my_list)
print(type(my_list))

[1, 2, 3, 4, 5, 6, 7]
<class 'list'>


In [8]:
# passing list to array
a = np.array(my_list)
print(a)

[1 2 3 4 5 6 7]


In [23]:
print(type(a))
# n dimensional array

<class 'numpy.ndarray'>


ndim

In [28]:
print("This is ", a.ndim ,"dimension array")
# to find number of dimension in array

This is  1 dimension array


size

In [26]:
print("The size of array is : ", a.size)
# no. of itens in array

The size of array is :  7


shape

In [29]:
print("Shape of array is : ", a.shape)
# shape of array 

Shape of array is :  (7,)


## n dimension array

In [18]:
my_matrix = [[1,2,3,4],[8,7,6,5],[2,9,0,4]]
print(my_matrix)

[[1, 2, 3, 4], [8, 7, 6, 5], [2, 9, 0, 4]]


In [19]:
print(type(my_matrix))

<class 'list'>


In [21]:
arr2 = np.array(my_matrix)
print(arr2)
# generating a 2D array

[[1 2 3 4]
 [8 7 6 5]
 [2 9 0 4]]


In [22]:
print(type(arr2))

<class 'numpy.ndarray'>


In [30]:
print("This is ", arr2.ndim ,"dimension array")

This is  2 dimension array


In [31]:
print('The size of array:', arr2.size)

The size of array: 12


In [32]:
print('The datatype of element:', arr2.dtype)

The datatype of element: int32


In [34]:
print('The shape of array is :', arr2.shape)

The shape of array is : (3, 4)


In [35]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[4,5,6],[1,2,3]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [1 2 3]]]


In [36]:
print("The shape of array is : ", arr3.shape)
# no. of lists, rows, column

The shape of array is :  (2, 2, 3)


In [37]:
print("This is ", arr3.ndim ,"dimension array")

This is  3 dimension array


In [38]:
print('The size of array:', arr3.size)

The size of array: 12


## Built-in Methods

## 1. reshape()

In [39]:
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [1 2 3]]]


In [40]:
arr3.shape

(2, 2, 3)

In [42]:
new_arr3 = arr3.reshape((1,6,2))
print(new_arr3)
# change the shape of an existing array without altering its data
# The total number of elements in the new shape must match the total number of elements in the original array

[[[1 2]
  [3 4]
  [5 6]
  [4 5]
  [6 1]
  [2 3]]]


In [45]:
print(new_arr3.shape)

(1, 6, 2)


In [49]:
new_arr3 = arr3.reshape((3,4))
print(new_arr3)

[[1 2 3 4]
 [5 6 4 5]
 [6 1 2 3]]


In [50]:
print(new_arr3.shape)

(3, 4)


Reshape a 1D array into a 2D array

In [58]:
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape((2, 3))
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [59]:
new_arr.ndim

2

Reshape a 2D array into a 3D array

In [55]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
new_arr = arr.reshape((2,1,3))
print(new_arr)

[[[1 2 3]]

 [[4 5 6]]]


In [57]:
new_arr.ndim

3

## 2. arange()

Return evenly spaced values within a given interval

In [63]:
np.arange(15) # end, default start from 0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [65]:
np.arange(50,1,-5) # start, end, step

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5])

In [66]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

## 3. zeros and ones

Generate arrays of zeros or ones

In [3]:
np.zeros(5)
# generate 1d array with all elements 0

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros((2,3))
# generate 2d array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
np.ones(3)
# generate 1d array with all elements 1

array([1., 1., 1.])

In [11]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.ones((4,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

## 4. linspace()

In [14]:
np.linspace(1,15)
# prints default 50 observations
# generate evenly spaced numbers over a specified range
# both the start and end are included in the array

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [24]:
np.linspace(0,100,5)
# prints evenly spaced 5 values starting from 0 till 100
# ending value must be n+1

array([  0.,  25.,  50.,  75., 100.])

In [26]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
np.linspace(0,100,11,retstep=True) 
# shows the difference between two elements

(array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.]),
 10.0)

## 5. eye()

Creates an identity matrix

In [28]:
np.eye(4)
# generates 2d array of (4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 6. Broadcasting in an array

The ability to access each and every element of an array is known as Broadcasting

In [30]:
my_arr = np.ones((2,3))
print(my_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [35]:
print(my_arr*4)

[[4. 4. 4.]
 [4. 4. 4.]]


In [36]:
print(my_arr*6-3)

[[3. 3. 3.]
 [3. 3. 3.]]


In [34]:
bigger=np.array(my_arr*3 - 0.4, dtype='int')
print(bigger)

[[2 2 2]
 [2 2 2]]


In [37]:
print(bigger.dtype)

int32


In [38]:
print(type(bigger))

<class 'numpy.ndarray'>


In [40]:
print(bigger.size)

6


In [41]:
print(bigger.shape)

(2, 3)


In [42]:
print(bigger/bigger)

[[1. 1. 1.]
 [1. 1. 1.]]


In [43]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [44]:
print(arr + arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [45]:
print(arr ** 2)

[ 0  1  4  9 16 25 36 49 64 81]


## 7. copy()

In [46]:
arr1 = [1,2,3,4]
arr2 = [4,5,6,7]
print(arr1)
print(arr2)

[1, 2, 3, 4]
[4, 5, 6, 7]


Shallow copy

In [53]:
arr1 = arr2
arr1
# shallow copy not recommended as it changes the original value of elements in array

[4, 5, 6, 7]

Deep copy

In [55]:
arr3 = [1,2,3,4]
arr4 = [4,5,6,7]
print(arr3)
print(arr4)

[1, 2, 3, 4]
[4, 5, 6, 7]


In [57]:
copy_arr3 = arr3.copy()
print("copy of arr3 : ",copy_arr3) # generates a copy / backup
print("arr3 : ",arr3)
print("arr4 : ",arr4)

copy of arr3 :  [1, 2, 3, 4]
arr3 :  [1, 2, 3, 4]
arr4 :  [4, 5, 6, 7]


In [58]:
slicing_arr = np.arange(20)
print(slicing_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [60]:
slicing_arr[:10] = 30
print(slicing_arr)

[30 30 30 30 30 30 30 30 30 30 10 11 12 13 14 15 16 17 18 19]


In [61]:
slicing_arr[10:] = 100
print(slicing_arr)

[ 30  30  30  30  30  30  30  30  30  30 100 100 100 100 100 100 100 100
 100 100]


## 8. rand()

In [65]:
random_number = np.random.rand()
random_number
# prints any random number between 0 and 1

0.2340685444326014

In [64]:
random_numbers = np.random.rand(10)
random_numbers
# prints 10 random number between 0 and 1

array([0.65761421, 0.56930241, 0.81273322, 0.52974617, 0.88170992,
       0.9158096 , 0.43192951, 0.73578125, 0.33239163, 0.64452605])

In [69]:
reshaped_numbers = random_numbers.reshape((2, 5))
print(reshaped_numbers)

[[0.65761421 0.56930241 0.81273322 0.52974617 0.88170992]
 [0.9158096  0.43192951 0.73578125 0.33239163 0.64452605]]


In [71]:
np.random.rand(12).reshape((6,2))

array([[0.70352817, 0.90808667],
       [0.02506224, 0.62379955],
       [0.21296939, 0.13671374],
       [0.81876444, 0.91140885],
       [0.33927893, 0.85930345],
       [0.78164936, 0.33690853]])

In [75]:
twod_arr = np.random.rand(3,3)
print(twod_arr)

[[0.55785412 0.35990535 0.72302111]
 [0.82890047 0.17737354 0.29890735]
 [0.71054809 0.00405271 0.3529113 ]]


## 9. randn()

Returns a sample from standard normal distribution (range -3 to 3)

In [77]:
randn_arr = np.random.randn(50)
print(randn_arr)

[-0.03476997 -0.21977915  0.17374993  0.12521918 -0.03109224 -2.05235489
  0.40920779  0.17566566 -0.01227193 -0.83068045  0.20541964  0.4537362
 -0.12562594  1.23220643 -0.53576095  1.97921626  0.90471044  0.08638071
 -0.91249072  0.06043925 -0.11695206  0.3226445   0.28250949  0.6975977
  0.31605747 -0.04874907  0.10547094  0.9198783  -0.63724728 -0.03388498
 -0.7515377  -0.06030347 -1.43487993  1.01270982  1.36474716  0.17494527
  0.73018703 -0.40274723  2.0549746   2.5488443   0.39540596 -0.57369112
  0.70846263  1.53208648 -0.0469775   0.40743277  0.5405894  -2.28357114
 -0.20265979  0.83242197]


In [78]:
max(randn_arr)

2.5488442989007094

In [79]:
min(randn_arr)

-2.2835711357369712

In [80]:
np.random.randn(3,3)

array([[-0.76331514, -0.3427408 ,  0.54655052],
       [-0.17666539, -0.27889269,  0.67923447],
       [-0.99412919, -0.0096914 ,  0.04677845]])

## 10. randint()

In [81]:
np.random.randint(1,100)
# returns random value between 1 & 100 both inclusive

61

In [82]:
np.random.randint(1,100,10)

array([71, 54, 62,  4, 77, 63, 91, 42, 50, 16])

In [83]:
np.random.randint(40,60,50) # generating 50 values between 40 and 60

array([45, 49, 53, 41, 58, 41, 53, 59, 51, 52, 58, 52, 52, 53, 48, 50, 41,
       48, 54, 47, 42, 56, 47, 55, 41, 57, 58, 43, 51, 59, 53, 54, 41, 43,
       46, 56, 40, 58, 55, 53, 48, 43, 58, 45, 44, 54, 51, 46, 49, 51])

## Array Attributes and Methods

In [84]:
arr = np.arange(20)
ranarr = np.random.randint(0,100,10)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [85]:
ranarr

array([57, 11, 10, 27, 90, 63, 78, 12, 55, 62])

In [86]:
ranarr.argmax() 
# Index location of highest element

4

In [87]:
ranarr.min() 
# Gives the lowest element of array

10

In [88]:
ranarr.argmin() 
# Index location of lowest element

2