# NumPy 
NumPy is a Linear Algebra Library in Python and it is the holy grail and the main building block of Data Science using Python. Almost all the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

It is bound to several C libraries which makes NumPy one of the fastest libraries in Python.

We will learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you don't have Anaconda, install NumPy by going to your terminal or command prompt and type:**
    
    !pip install numpy
    conda install numpy
    


## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. 

# Numpy Arrays

Numpy arrays essentially of two types: vectors and matrices. Vectors are strictly 1-D arrays and matrices are 2-D (Note: A matrix can still have only one row or one column).

The following cells explain on creation of NumPy arrays.

## Creating NumPy Arrays

### From a Python List

An array can be created by directly converting a list or list of lists:

In [2]:
import numpy as np

In [3]:
arr1 = np.array([])   # create an empty array
arr1

array([], dtype=float64)

In [4]:
my_list = [1,2,3,4,5]
print(my_list)
print(type(my_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [5]:
a=np.array(my_list)

In [6]:
a

array([1, 2, 3, 4, 5])

In [7]:
type(a)   # ndarray is number dimension array

numpy.ndarray

In [8]:
a.ndim  # number of dimensions in the array

1

In [9]:
a.size  # size of an array is the no. of items 

5

In [10]:
a.shape # shape of array

(5,)

#### Arrays can be of n dimensions.

In [14]:
my_matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]] # list of lists
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [15]:
import numpy as np
b=np.array(my_matrix) # generates a 2-d array
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
# Array summary
print('The Dimension of array',b.ndim) # dimensions of given array

The Dimension of array 2


In [17]:
print('The size of array:',b.size) # Number of elements in array

The size of array: 12


In [18]:
print('The datatype of element:',b.dtype) # Datatype of elements in array

The datatype of element: int32


In [21]:
print('The type of structure:',type(b))

The type of structure: <class 'numpy.ndarray'>


In [20]:
print('The shape:',b.shape)

The shape: (3, 4)


In [22]:
b.shape

(3, 4)

In [2]:
import numpy as np

In [3]:
arr1= np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [26]:
arr1.shape

(2, 2, 3)

In [27]:
arr1.ndim

3

In [28]:
arr1.size

12

## Built-in Methods

There are lots of built-in ways to generate Arrays

### Reshape function

In [4]:
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
arr1.shape

(2, 2, 3)

In [6]:
arr2=arr1.reshape((1,3,4))  # reshape function takes the new shape as its argument

In [7]:
arr2.shape

(1, 3, 4)

In [10]:
arr2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [11]:
arr2=arr1.reshape((3,4))

In [14]:
arr2.ndim

2

### arange

Return evenly spaced values within a given interval.

In [40]:
#np.arange(start,end,step)

In [27]:
np.arange(15) # end; default start at 0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
np.arange(100,2,-4) # start, end and step

array([100,  96,  92,  88,  84,  80,  76,  72,  68,  64,  60,  56,  52,
        48,  44,  40,  36,  32,  28,  24,  20,  16,  12,   8,   4])

In [29]:
np.arange(0,11,2) # start end and step

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [34]:
import numpy as np

In [30]:
np.zeros(3) # Generates array in 1 dimension with all elements 0

array([0., 0., 0.])

In [31]:
np.zeros((5,5))  # Generates array in 2 diemnsions with all elements 0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.ones(3) # Generates array of 1 dimension where all elements are 1

array([1., 1., 1.])

In [33]:
np.ones((4,5)) # Generates array of  dimensions where all elements are 1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
np.ones((4,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

### linspace
Return evenly spaced numbers over a specified interval.

In [1]:
import numpy as np

In [35]:
np.linspace(1,15)  # default 50 observations
# both the start and end are included in the array

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [41]:
np.linspace(5,25,100)  # equally spaced 10 values

array([ 5.        ,  5.2020202 ,  5.4040404 ,  5.60606061,  5.80808081,
        6.01010101,  6.21212121,  6.41414141,  6.61616162,  6.81818182,
        7.02020202,  7.22222222,  7.42424242,  7.62626263,  7.82828283,
        8.03030303,  8.23232323,  8.43434343,  8.63636364,  8.83838384,
        9.04040404,  9.24242424,  9.44444444,  9.64646465,  9.84848485,
       10.05050505, 10.25252525, 10.45454545, 10.65656566, 10.85858586,
       11.06060606, 11.26262626, 11.46464646, 11.66666667, 11.86868687,
       12.07070707, 12.27272727, 12.47474747, 12.67676768, 12.87878788,
       13.08080808, 13.28282828, 13.48484848, 13.68686869, 13.88888889,
       14.09090909, 14.29292929, 14.49494949, 14.6969697 , 14.8989899 ,
       15.1010101 , 15.3030303 , 15.50505051, 15.70707071, 15.90909091,
       16.11111111, 16.31313131, 16.51515152, 16.71717172, 16.91919192,
       17.12121212, 17.32323232, 17.52525253, 17.72727273, 17.92929293,
       18.13131313, 18.33333333, 18.53535354, 18.73737374, 18.93

In [ ]:
# retstep ~ return step computed by linspace

In [43]:
np.linspace(0,25, retstep=True) # Start # end (Here end is included) and default elements are 50

(array([ 0.        ,  0.51020408,  1.02040816,  1.53061224,  2.04081633,
         2.55102041,  3.06122449,  3.57142857,  4.08163265,  4.59183673,
         5.10204082,  5.6122449 ,  6.12244898,  6.63265306,  7.14285714,
         7.65306122,  8.16326531,  8.67346939,  9.18367347,  9.69387755,
        10.20408163, 10.71428571, 11.2244898 , 11.73469388, 12.24489796,
        12.75510204, 13.26530612, 13.7755102 , 14.28571429, 14.79591837,
        15.30612245, 15.81632653, 16.32653061, 16.83673469, 17.34693878,
        17.85714286, 18.36734694, 18.87755102, 19.3877551 , 19.89795918,
        20.40816327, 20.91836735, 21.42857143, 21.93877551, 22.44897959,
        22.95918367, 23.46938776, 23.97959184, 24.48979592, 25.        ]),
 0.5102040816326531)

In [44]:
np.linspace(0,200,10) # default retstep=False

array([  0.        ,  22.22222222,  44.44444444,  66.66666667,
        88.88888889, 111.11111111, 133.33333333, 155.55555556,
       177.77777778, 200.        ])

In [45]:
np.linspace(0,200,10,retstep=True)

(array([  0.        ,  22.22222222,  44.44444444,  66.66666667,
         88.88888889, 111.11111111, 133.33333333, 155.55555556,
        177.77777778, 200.        ]),
 22.22222222222222)

### eye

Creates an identity matrix

In [37]:
np.eye(5)   # generates 2d array of (5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Create an eye from a zeros array

### Broadcasting in an array

In [38]:
big_one=np.ones((3,4))
print(big_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [39]:
big_one.dtype

dtype('float64')

In [40]:
big_one * 3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

#### The ability to access each and every element of an array is known as Broadcasting.

In [41]:
bigger_one=big_one*6 - 2
bigger_one

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [42]:
bigger=np.array(big_one*3 - 0.4, dtype='int')
print(bigger)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [43]:
bigger.dtype

dtype('int32')

In [44]:
type(bigger)

numpy.ndarray

In [45]:
bigger.shape

(3, 4)

In [46]:
bigger/bigger

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
arr1 = np.arange(20)
1/arr1

C:\Users\Datamites\AppData\Local\Temp\ipykernel_1772\3219800275.py:2: RuntimeWarning: divide by zero encountered in divide
  1/arr1


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [43]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [44]:
arr1 + arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [45]:
arr1 ** arr1

array([          1,           1,           4,          27,         256,
              3125,       46656,      823543,    16777216,   387420489,
        1410065408,  1843829075,  -251658240, -1692154371, -1282129920,
        1500973039,           0,  1681328401,   457441280,  -306639989])

### Use of Copy function

In [16]:
arr2 = arr1 # not recommended
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
arr2[:10] = 30  # using indexing/slicing to modify arr2
arr2

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
arr1

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [55]:
arr3 = arr1.copy() # generate a copy / creates a backup

In [56]:
arr3[10:] = 100
arr3

array([ 30,  30,  30,  30,  30,  30,  30,  30,  30,  30, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

In [57]:
arr1  # copy function retains the original. copy creates a backup array.

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Random number generation

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [66]:
import numpy as np

In [71]:
np.random.rand()

0.7328238332464361

In [72]:
np.random.rand(10) # rand gives values between 0 and 1

array([0.83881909, 0.88861106, 0.66986904, 0.12763398, 0.88688772,
       0.40484848, 0.63907352, 0.74015214, 0.02334691, 0.93717532])

In [73]:
np.random.rand(10).reshape((2,5))

array([[0.10869166, 0.41984989, 0.31245584, 0.67564194, 0.43538348],
       [0.27663836, 0.41047921, 0.37234297, 0.43921256, 0.84832536]])

In [74]:
# Creating array from uniform distribution
new_arr=np.random.rand(5,3)
# 2 dimensional array of shape (5,3)

In [75]:
new_arr

array([[0.89949197, 0.24177503, 0.65447647],
       [0.75829511, 0.62128744, 0.39649584],
       [0.5160491 , 0.81365486, 0.49313968],
       [0.39154554, 0.18293142, 0.2739831 ],
       [0.58654753, 0.87057993, 0.88474012]])

In [76]:
np.random.rand(3,3)

array([[0.44753075, 0.87427983, 0.58314794],
       [0.66720042, 0.96265745, 0.33288852],
       [0.2132373 , 0.029161  , 0.89272049]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [ ]:
# For randn, random numbbers generated will be in approximately -3 to +3 range.

In [58]:
arr1=np.random.randn(50)  # 50 observations from std normal distribution
arr1

array([ 1.30254473,  0.60995183, -1.66392132,  0.57365554,  1.94722882,
        0.23195074,  0.3638552 , -0.78616466, -0.45406599,  2.05274468,
       -2.07759127,  0.55295073,  0.25130103,  0.35540126,  0.92872071,
        1.33499022, -0.37777744,  0.98161535,  0.13246939,  0.5341624 ,
        1.0172765 , -0.490377  , -1.28144631,  1.30332725,  0.96748491,
        0.88197572, -0.97263774, -0.81484054,  1.26236146, -1.59739083,
       -0.30270169,  0.20190896,  0.53857411,  0.30003658, -0.55358837,
       -0.26127983,  0.67973228,  0.24794669, -0.55580123, -0.36608769,
       -0.16674865, -0.5160711 ,  1.85625107, -1.55442596,  1.54315905,
       -0.7607191 , -0.77159432,  1.23985549, -0.82057639,  0.22341264])

In [83]:
max(arr1)

2.7036184469049256

In [61]:
# a=np.array([[[[[[[[[[[1,2,3,4]]]]]]]]]]])
# a.ndim

In [84]:
min(arr1)

-1.9200629716978184

In [85]:
np.random.randn(3,3)

array([[ 0.34212081, -1.81779625,  0.60060757],
       [-0.7926928 , -0.41214329,  0.3947043 ],
       [-0.01703567,  0.38264877, -0.1985096 ]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [62]:
np.random.randint(1,100) 
# third argument is no. of values. default =1 value

21

In [63]:
np.random.randint(1,100,10)

array([18, 89, 25, 87,  4, 16, 32, 66, 45,  1])

In [64]:
np.random.randint(40,60,50) # generating 50 values between 

array([47, 56, 49, 40, 42, 53, 55, 53, 58, 47, 48, 41, 43, 51, 59, 45, 41,
       52, 54, 49, 56, 43, 51, 43, 42, 46, 42, 53, 42, 48, 47, 57, 50, 50,
       58, 49, 40, 46, 47, 44, 52, 49, 54, 58, 56, 42, 51, 57, 42, 49])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [65]:
arr = np.arange(20)
ranarr = np.random.randint(0,100,10)

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [67]:
ranarr

array([93,  6, 15, 67, 35, 14, 75, 99, 38, 90])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [68]:
ranarr

array([93,  6, 15, 67, 35, 14, 75, 99, 38, 90])

In [69]:
ranarr.max() # highest element of the array

99

In [70]:
arr.max()

19

In [71]:
ranarr.argmax() ## Index location of highest element

7

In [72]:
ranarr.min() # Gives the lowest element of array

6

In [73]:
ranarr.argmin() # Index location of lowest element

1

In [13]:
#ran2=ranarr.reshape(2,5)

In [14]:
#ran2

In [34]:
ran2.argmax()

7

In [ ]:
ran2.max()

# Happy Learning!