In [1]:
import numpy as np

In [2]:
arr1 = np.array([])
arr1
#default datatype of elements of array is float

array([], dtype=float64)

In [3]:
my_list = [10,20,30,40]
print(my_list)
type(my_list)

[10, 20, 30, 40]


list

In [4]:
a = np.array(my_list)
print(a)
type(a)

[10 20 30 40]


numpy.ndarray

In [5]:
a.ndim #number of dimentions in array

1

In [6]:
a.size #no. of items

4

In [7]:
a.shape #no. of rows and column

(4,)

In [8]:
my_matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
print(my_matrix)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [9]:
b = np.array(my_matrix)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
b.ndim

2

In [11]:
b.size

12

In [12]:
b.shape

(3, 4)

In [13]:
type(b)

numpy.ndarray

In [14]:
b.dtype # check type of element of array

dtype('int32')

In [15]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[4,5,6],[7,8,9]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]]


In [16]:
arr3.ndim

3

In [17]:
arr3.size

12

In [18]:
arr3.shape #(no. of lists, rows, columns)

(2, 2, 3)

## reshape()

In [19]:
arr4 = arr3.reshape((1,3,4))
arr4

array([[[1, 2, 3, 4],
        [5, 6, 4, 5],
        [6, 7, 8, 9]]])

In [20]:
arr4.shape

(1, 3, 4)

In [21]:
arr4 = arr3.reshape((1,6,2))
arr4

array([[[1, 2],
        [3, 4],
        [5, 6],
        [4, 5],
        [6, 7],
        [8, 9]]])

In [22]:
arr4.ndim

3

## arange()

In [23]:
np.arange(15) #end, default start from 0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
np.arange(100,2,-5) #start,end,step

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25,  20,  15,  10,   5])

## zeros and ones

In [25]:
zero_arr = np.zeros(3) # generate 1D array with all elements 0
print(zero_arr)

[0. 0. 0.]


In [26]:
zero_arr = np.zeros((5,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
ones_arr = np.ones(5)
print(ones_arr)

[1. 1. 1. 1. 1.]


In [28]:
ones_arr = np.ones((5,5))
print(ones_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## linspace

In [29]:
np.linspace(1,15) #print default 50 values

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [30]:
np.linspace(0,100,5) # prints 10 values from 0 to 100 which are equally divided in 10 parts

array([  0.,  25.,  50.,  75., 100.])

In [31]:
np.linspace(0,100,11) # last value in n+1

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [32]:
np.linspace(0,100,11,retstep=True) # shows the difference between two elements

(array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.]),
 10.0)

## eye

In [33]:
identity = np.eye(5) # used to print identity matrix
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## copy function

In [34]:
arr1 = [1,2,3,4]
arr2 = [4,5,6,7]

In [35]:
arr2 = arr1

In [36]:
copy = arr1.copy() # deep copy

In [37]:
copy

[1, 2, 3, 4]

In [38]:
arr1

[1, 2, 3, 4]

In [39]:
arr1 = arr2 # shallow copy

In [44]:
arr2

[1, 2, 3, 4]

In [41]:
# shallow copy not recommended as it changes the original value 

In [55]:
arr1 = np.array([])
my_arr = [1,2,3,4,5,6,7,8,9,0]
a = np.array(my_arr)

In [56]:
a[:3] = 4
a

array([4, 4, 4, 4, 5, 6, 7, 8, 9, 0])

In [57]:
a[4:] = 5
a

array([4, 4, 4, 4, 5, 5, 5, 5, 5, 5])

## random

In [60]:
np.random.rand() # returns any random value between 0 to 1

0.07452352889567915

In [61]:
np.random.rand(10)

array([0.25152747, 0.69353329, 0.12254463, 0.36841518, 0.83496303,
       0.33656906, 0.20942662, 0.10697639, 0.14908604, 0.83727031])

In [65]:
np.random.rand(10).reshape((2,5))

array([[0.57129717, 0.10326165, 0.38519295, 0.28494428, 0.16119285],
       [0.81395271, 0.36305038, 0.366227  , 0.5378458 , 0.34690102]])

In [70]:
np.random.randn() # for values in range of normal distribution (-3 to +3)

-1.383751389372952

In [73]:
np.random.randn(10)

array([-1.51288098, -0.68204045,  1.80453072, -0.20630198,  1.22038461,
        0.50868092, -0.37769097, -0.78859231, -0.55486133,  0.45699545])

## radint

In [81]:
np.random.randint(1,100) # returns random value between 1 & 100 both inclusive

65

In [82]:
np.random.randint(1,100,10)

array([31,  6, 87, 22, 28, 35, 66, 40,  2, 69])